Add year to all workshop URLs
warsztatywww/aplikacjawww pull request #243
Opened 2020-08-22 10:50 UTC by krzys-h

This changes the URL schema of workshops to `https://warsztatywww.pl/{year}/workshop/{name}/`. This means that workshop names no longer have to be unique, only the year-name pair has to be. I also moved some URLs under under `/workshop/` that should have logically been there (register/unregister and qual problems)

As a part of this change, I had to move the year directly to the Workshop model, rather than accessing it through the category (`workshop.type.year` -> `workshop.year`), since the unique_together constraint couldn't work otherwise. This is probably better for the database anyway.

To be merged after #230

Closes #242

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243)

2020-09-15 03:14 UTC, cytadela8 requested changes
- Please remove obsolete file `fixtures/simpletestdata.json`

- Please rebase on top of Licence to grant AGPL v3 licence.

- `./manage.py populate_with_test_data` is broken: `django.db.utils.IntegrityError: NOT NULL constraint failed: wwwapp_workshop.year_id`

> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243#-:-MHEhBI82R1BccXmSNFh:b-cj2hgi)* status: all files reviewed, 2 unresolved discussions (waiting on @krzys-h)

___
*[wwwapp/views.py, line 281 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243#-MHEhh7h9ljIlwbLNTw1:-MHEhh7h9ljIlwbLNTw2:b-4iyto) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/6b604cdd6787fa9e039dd8faa27439c292e27343/wwwapp/views.py#L281)):*
> ```Python
>                 workshop = form.save(commit=False)
>                 if new:
>                     assert workshop.year == year
> ```

It's generally not good to use asserts as they may be disabled in production environment. Raise exception instead.
___
*[wwwapp/views.py, line 316 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243#-MHEi1N4ANBRkUPk8i3C:-MHEi1N4ANBRkUPk8i3D:b-fuvyhv) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/6b604cdd6787fa9e039dd8faa27439c292e27343/wwwapp/views.py#L316)):*
> ```Python
> def legacy_workshop_redirect_view(request, name):
>     # To keep the old links working
>     workshop = get_object_or_404(Workshop, name=name, year__year__lte=2020)
> ```

Minor, I want to change year to string from int later. Could you query and sort by date and get oldest instead maybe?


<!-- Sent from Reviewable.io -->

2020-09-25 08:56 UTC, krzys-h reviewed
> Please remove obsolete file fixtures/simpletestdata.json
Done

> Please rebase on top of Licence to grant AGPL v3 licence.
Done

> ./manage.py populate_with_test_data is broken: django.db.utils.IntegrityError: NOT NULL constraint failed: wwwapp_workshop.year_id
Done

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243#-:-MI3Qu2T2AzQpFFOms5T:blp5439)* status: 17 of 19 files reviewed, 2 unresolved discussions (waiting on @cytadela8 and @krzys-h)

___
*[wwwapp/views.py, line 281 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243#-MHEhh7h9ljIlwbLNTw1:-MI3R4B4DeGi3AvT0UE3:b-k8ygg0) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/6b604cdd6787fa9e039dd8faa27439c292e27343/wwwapp/views.py#L281)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

It's generally not good to use asserts as they may be disabled in production environment. Raise exception instead.
</blockquote></details>

But in this case it makes sense - it will never happen unless somebody messes up the `new == not workshop` assumption. This is what asserts were made for. Additionally I cleaned up the new/workshop situation in #240 so this assert can probably be removed entirely after these two branches are merged together.
___
*[wwwapp/views.py, line 316 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243#-MHEi1N4ANBRkUPk8i3C:-MI3SQSF1Uc96jPtAoUd:b-9w631v) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/6b604cdd6787fa9e039dd8faa27439c292e27343/wwwapp/views.py#L316)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Minor, I want to change year to string from int later. Could you query and sort by date and get oldest instead maybe?
</blockquote></details>

I kinda wanted to prevent people from using this endpoint as a "oh cool, a shortened URL" endpoint. If we sort by oldest, this endpoint would also work for new workshops (as long as they have unique names). Is that what we want here?


<!-- Sent from Reviewable.io -->

2020-12-28 18:25 UTC, cytadela8 requested changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243)* status: all files reviewed, 2 unresolved discussions (waiting on @krzys-h)

___
*[wwwapp/views.py, line 316 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243#-MHEi1N4ANBRkUPk8i3C:-MPeZWqi25Ono2QwHmjP:biblshj) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/6b604cdd6787fa9e039dd8faa27439c292e27343/wwwapp/views.py#L316)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

I kinda wanted to prevent people from using this endpoint as a "oh cool, a shortened URL" endpoint. If we sort by oldest, this endpoint would also work for new workshops (as long as they have unique names). Is that what we want here?
</blockquote></details>

I think we can allow it. Or you can just change the comparison to work on some creation date field. My issue is that we will probably want to remove the current year field in favour of some "edition" string or something like that (to allow multiple editions per year for things like WWWx), so I don't want to create new dependencies on `year`
___
*[wwwapp/management/commands/populate_with_test_data.py, line 122 at r3](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243#-MPea6Be3AyGAagHBMcd:-MPea6Be3AyGAagHBMce:bcgn3hw) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/0f323ae21340138aa1fa16c7061aebda2932d4b0/wwwapp/management/commands/populate_with_test_data.py#L122)):*
> ```Python
>                       categories: List[WorkshopCategory],
>                       sequence: Union[str, None] = None) -> Workshop:
>         type = random.choice(types)
> ```

Type is a Python keyword. Please don't overwrite keywords...


<!-- Sent from Reviewable.io -->

2020-12-28 21:16 UTC, krzys-h reviewed
Merge carefully - there was A TON of rebasing I had to do

I also modified the editor very slightly to display the URL slug value in the middle of an actual URL which includes the year. Hopefully this should help people notice that it no longer has to be unique.

![image.png](https://files.reviewableusercontent.io/images/reviewable/1517255/AIwwVpqZom47nWyW9iKo-B9Y/image.png)

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243#-:-MPfBmnd8NMVH1oulJiw:bu691fb)* status: 5 of 19 files reviewed, 2 unresolved discussions (waiting on @cytadela8)

___
*[wwwapp/views.py, line 316 at r1](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243#-MHEi1N4ANBRkUPk8i3C:-MPfBkUJDAQJqgi2IhLS:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/6b604cdd6787fa9e039dd8faa27439c292e27343/wwwapp/views.py#L316)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

I think we can allow it. Or you can just change the comparison to work on some creation date field. My issue is that we will probably want to remove the current year field in favour of some "edition" string or something like that (to allow multiple editions per year for things like WWWx), so I don't want to create new dependencies on `year`
</blockquote></details>

Done.
___
*[wwwapp/management/commands/populate_with_test_data.py, line 122 at r3](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243#-MPea6Be3AyGAagHBMcd:-MPfBlG-9_n7Ie9E-M6j:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/0f323ae21340138aa1fa16c7061aebda2932d4b0/wwwapp/management/commands/populate_with_test_data.py#L122)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Type is a Python keyword. Please don't overwrite keywords...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-30 12:31 UTC, cytadela8 requested changes
> Reviewed 13 of 13 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243)* status: all files reviewed, 2 unresolved discussions (waiting on @krzys-h)

___
*[wwwapp/forms.py, line 160 at r4](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243#-MPnaY7y7CBh6ovRXbZ4:-MPnaY7y7CBh6ovRXbZ5:b-jsfugj) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/89dd6a0f39f93cda860367078c7048a4ff7e7fa0/wwwapp/forms.py#L160)):*
> ```Python
>         self.helper.include_media = False
>         mce_attrs = {}
>         if kwargs['instance'] and kwargs['instance'].pk:
> ```

Why do we need to add this?
___
*[wwwapp/views.py, line 25 at r7](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243#-MPnbO8DBk86MnHCKixJ:-MPnbO8DBk86MnHCKixK:bgc0oc0) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/b6094f15b15b985e24fab9d2cf6e32115a12e460/wwwapp/views.py#L25)):*
> ```Python
> from django.db.models import Q
> from django.http import JsonResponse, HttpResponse, HttpRequest, HttpResponseForbidden
> from django.http.response import HttpResponseBadRequest, HttpResponseNotFound, Http404
> ```

This is unused?


<!-- Sent from Reviewable.io -->

2020-12-30 13:31 UTC, krzys-h reviewed
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243)* status: all files reviewed, 2 unresolved discussions (waiting on @cytadela8 and @krzys-h)

___
*[wwwapp/forms.py, line 160 at r4](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243#-MPnaY7y7CBh6ovRXbZ4:-MPnmwDw-49N98R6pmUm:b29iqpk) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/89dd6a0f39f93cda860367078c7048a4ff7e7fa0/wwwapp/forms.py#L160)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Why do we need to add this?
</blockquote></details>

The instance is now always passed, even for new objects, because `.year` is set in the controller and the form uses it to determine which cateories are valid selections. Before #240 this if was only in the public page editing code path where the object was already saved in the database if it was passed at all. The original intention of this condition was "the object is saved in the database with a name which is unlikely to change" (since it's used as a part of uploaded file path)

And I just noticed this is the article one - we don't need it here, but we do in workshop editor and I wanted to keep the code the same in both.
___
*[wwwapp/views.py, line 25 at r7](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243#-MPnbO8DBk86MnHCKixJ:-MPnlG1V9GsU4EGw2IkE:b-yu20q2) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/b6094f15b15b985e24fab9d2cf6e32115a12e460/wwwapp/views.py#L25)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

This is unused?
</blockquote></details>

My bad, this is from before I realized get_object_or_404 cantake a QuerySet as an argument and copied a bit of code from it. Will fix in a second.


<!-- Sent from Reviewable.io -->

2020-12-30 13:57 UTC, krzys-h reviewed
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243)* status: 14 of 20 files reviewed, 1 unresolved discussion (waiting on @cytadela8 and @krzys-h)

___
*[wwwapp/views.py, line 25 at r7](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243#-MPnbO8DBk86MnHCKixJ:-MPnw9QtBrl2Xzs2pIZ_:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/b6094f15b15b985e24fab9d2cf6e32115a12e460/wwwapp/views.py#L25)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

My bad, this is from before I realized get_object_or_404 cantake a QuerySet as an argument and copied a bit of code from it. Will fix in a second.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-30 14:40 UTC, cytadela8 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 2 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/243#-:-MPo4tLdCmvGmBNfguwv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-30 14:40 UTC, merged