static hosting - versioned paths and remove dj-static
warsztatywww/aplikacjawww pull request #301
Opened 2021-01-11 18:20 UTC by cytadela8

2021-01-12 20:22 UTC, krzys-h requested changes
Note: I only looked at the diff right now, I'll run it to check if it works later. I'm particularly afraid of finding some legacy code somewhere which doesn't use the `static` tag which could break `ManifestStaticFilesStorage` - I know there were cases of not using the `url` tag properly in the past

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/301#-:-MQsE_DL-NFrdkyFGViS:b-2vn1gm)* status: all files reviewed, 1 unresolved discussion (waiting on @cytadela8)

___
*[wwwapp/wsgi.py, line 14 at r2](https://reviewable.io/reviews/warsztatywww/aplikacjawww/301#-MQsDahH30AHIuaO4Gi3:-MQsDahIAjcY2MruM27G:bdjm35q) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/fb67a46b1f67ccba3750086ddb5c8696dc111b06/wwwapp/wsgi.py#L14)):*
> ```Python
> 
> from django.core.wsgi import get_wsgi_application
> application = get_wsgi_application()
> ```

This reminds me - there is another (probably unused) copy of this file at `wsgi/application`. I was going to ask you which one is used in prod config and then forgot, please remove the other one.


<!-- Sent from Reviewable.io -->

2021-01-12 20:52 UTC, cytadela8 reviewed
I have grepped for "static" in codebase and found a path in settings_common. This is the only place where we do not use static path resolution

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/301#-:-MQsMZQn8jD0pOfiZ4ID:bubgqvd)* status: all files reviewed, 1 unresolved discussion (waiting on @cytadela8)

___
*[wwwapp/wsgi.py, line 14 at r2](https://reviewable.io/reviews/warsztatywww/aplikacjawww/301#-MQsDahH30AHIuaO4Gi3:-MQsMVlQ3XLh2oDzZdF2:b-a5067o) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/fb67a46b1f67ccba3750086ddb5c8696dc111b06/wwwapp/wsgi.py#L14)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

This reminds me - there is another (probably unused) copy of this file at `wsgi/application`. I was going to ask you which one is used in prod config and then forgot, please remove the other one.
</blockquote></details>

Thanks I will remove one of those files


<!-- Sent from Reviewable.io -->

2021-01-14 15:30 UTC, krzys-h reviewed
Yeah, tinymce doesn't load from the hashed path, but still works since it looks like `ManifestStaticFilesStorage` makes it available at both paths. It should be fixed though.

Other than that (and my request to remove one of the duplicated wsgi files) it seems to work.

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/301#-:-MR0Vnjp06pZU7HgodK_:bpxlqlv)* status: all files reviewed, 1 unresolved discussion (waiting on @cytadela8)



<!-- Sent from Reviewable.io -->

2021-01-16 21:43 UTC, cytadela8 reviewed
Fixed TinyMCE to load from hashed path.

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/301#-:-MRC8bH16RlGYmPC8aFq:b-fqwdzf)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @krzys-h)

___
*[wwwapp/wsgi.py, line 14 at r2](https://reviewable.io/reviews/warsztatywww/aplikacjawww/301#-MQsDahH30AHIuaO4Gi3:-MRC8hEH-uGY86P0kWns:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/fb67a46b1f67ccba3750086ddb5c8696dc111b06/wwwapp/wsgi.py#L14)):*
<details><summary><i>Previously, cytadela8 (Artur Puzio) wrote…</i></summary><blockquote>

Thanks I will remove one of those files
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-16 22:47 UTC, krzys-h requested changes
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/301)* status: all files reviewed, 1 unresolved discussion (waiting on @cytadela8)

___
*[wwwapp/forms.py, line 23 at r4](https://reviewable.io/reviews/warsztatywww/aplikacjawww/301#-MRCMwF46VoOaokDRP86:-MRCMwF46VoOaokDRP87:b-75uy52) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/685c8f04269ef12c894417269e22dd3534dbe03a/wwwapp/forms.py#L23)):*
> ```Python
> class InitializedTinyMCE(tinymce.widgets.TinyMCE):
>     def __init__(self, mce_attrs=None, **kwargs):
>         mce_attrs_all = settings.TINYMCE_DEFAULT_CONFIG_WITH_IMAGES.copy()
> ```

This is wrong. `TINYMCE_DEFAULT_CONFIG_WITH_IMAGES` should only be used in editors where image uploads are supported. Also, the TinyMCE widget constructor already joins the passed options with `TINYMCE_DEFAULT_CONFIG`, so just use `{}` here.


<!-- Sent from Reviewable.io -->

2021-01-16 23:06 UTC, cytadela8 reviewed
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/301)* status: all files reviewed, 1 unresolved discussion (waiting on @krzys-h)

___
*[wwwapp/forms.py, line 23 at r4](https://reviewable.io/reviews/warsztatywww/aplikacjawww/301#-MRCMwF46VoOaokDRP86:-MRCRfWC1rKAFdlmbEFT:b-896fix) ([raw file](https://github.com/warsztatywww/aplikacjawww/blob/685c8f04269ef12c894417269e22dd3534dbe03a/wwwapp/forms.py#L23)):*
<details><summary><i>Previously, krzys-h (krzys_h) wrote…</i></summary><blockquote>

This is wrong. `TINYMCE_DEFAULT_CONFIG_WITH_IMAGES` should only be used in editors where image uploads are supported. Also, the TinyMCE widget constructor already joins the passed options with `TINYMCE_DEFAULT_CONFIG`, so just use `{}` here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-16 23:08 UTC, krzys-h approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/301)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-22 16:49 UTC, krzys-h reviewed
> Reviewed 6 of 6 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/301)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @krzys-h)



<!-- Sent from Reviewable.io -->

2021-01-22 16:49 UTC, krzys-h approved these changes
:duck: 

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/301#-:-MRf-8Jw90goBNXPe6uu:bcmjph0)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @krzys-h)



<!-- Sent from Reviewable.io -->

2021-01-22 20:44 UTC, cytadela8 reviewed
:duck: tylko kliknij jakoś skutecznie ten approve, bo na razie nie jest reviowed do końca

> *[Reviewable](https://reviewable.io/reviews/warsztatywww/aplikacjawww/301#-:-MRfpnh58mFu16KY_VmQ:b81qbhl)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @krzys-h)



<!-- Sent from Reviewable.io -->

2021-01-22 22:16 UTC, krzys-h approved these changes
:duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::duck::d [...]

2021-01-22 22:51 UTC, merged